dataset:
  type: imagenet
  root: /data/hujx/ATAS/atas-repro/datasets/ILSVRC2012_img_train
  image_size: 224
  collator: atas

train:
  batch_size: 36
  num_workers: 4
  epochs: 6
  lr: 1.0e-5
  weight_decay: 0.1
  save_dir: ./outputs/pretrain_bs36
  save_interval: 1
  amp: true

model:
  type: atas
  backbone:
    type: openai_clip
    model_name: ViT-B-16
    pretrained_name: null
    pretrained_path: /data/hujx/ATAS/atas-repro/pretrained_models/open_clip_pytorch_model.bin
    patch_grid_size: 14

loss:
  gld_weight: 1.0
  lld_weight: 0.01
  ggd_weight: 1.0
  tau: 0.1

logs:
  dir: ./logs/pretrain_bs36
  log_interval: 20

swanlab:
  enable: true
  project: ATAS
  name: atas_vit_b16_imagenet_bs36